global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
alerting:
    alertmanagers:
        - follow_redirects: true
          scheme: http
          timeout: 10s
          api_version: v2
          static_configs:
              - targets: []
scrape_configs:
    # Monitor Prometheus itself
    # prometheus-exporter
    - job_name: prometheus
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      static_configs:
          - targets:
                - localhost:9090
    # Monitor the Swarm Nginx Load Balancer
    # nginx-exporter
    - job_name: load_balancer
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      relabel_configs:
          - source_labels: [__meta_dockerswarm_service_name]
            target_label: __address__
            replacement: $1:9113
            action: replace
          - source_labels: [__meta_dockerswarm_task_desired_state]
            regex: running
            action: keep
          - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
            regex: nginx-exporter
            action: keep
          - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
            target_label: job
      dockerswarm_sd_configs:
          - follow_redirects: true
            host: http://captain-socket-proxy:2375
            role: tasks
    # Monitor Docker Swarm Nodes
    # node-exporter
    - job_name: nodes
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      relabel_configs:
          - source_labels: [__meta_dockerswarm_node_address]
            target_label: __address__
            replacement: $1:9100
            action: replace
          - source_labels: [__meta_dockerswarm_node_address]
            target_label: instance
            action: replace
      dockerswarm_sd_configs:
          - follow_redirects: true
            host: http://captain-socket-proxy:2375
            role: nodes
    # Monitor Docker Daemon
    # docker daemon.json metrics
    - job_name: docker
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      relabel_configs:
          - source_labels: [__meta_dockerswarm_node_address]
            target_label: __address__
            replacement: $1:9323
            action: replace
          - source_labels: [__meta_dockerswarm_node_address]
            target_label: instance
            action: replace
      dockerswarm_sd_configs:
          - follow_redirects: true
            host: http://captain-socket-proxy:2375
            role: nodes
    # Monitor Swarm Containers
    # CAdvisor
    - job_name: containers
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      follow_redirects: true
      relabel_configs:
          - source_labels: [__meta_dockerswarm_task_desired_state]
            regex: running
            action: keep
          - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
            regex: cadvisor
            action: keep
          - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
            target_label: job
      dockerswarm_sd_configs:
          - follow_redirects: true
            host: http://captain-socket-proxy:2375
            role: tasks
