scrape_configs:
    # Monitor Prometheus itself
    # prometheus-exporter
    - job_name: prometheus
      static_configs:
          - targets:
                - localhost:9090
    # Monitor the Swarm Nginx Load Balancer
    # nginx-exporter
    - job_name: load_balancer
      static_configs:
          - targets:
                - captain-nginx-exporter:9113
    # Monitor Docker Swarm Nodes
    # node-exporter
    - job_name: nodes
      static_configs:
          - targets:
                - 10.1.96.3:9100
                - 10.1.96.4:9100
    # Monitor Docker Daemon
    # docker daemon.json metrics
    - job_name: docker
      static_configs:
          - targets:
                - 10.1.96.3:9323
                - 10.1.96.4:9323
    # Monitor Swarm Containers
    # CAdvisor
    - job_name: containers
      static_configs:
          - targets:
                - 10.1.96.3:49153
                - 10.1.96.4:49153
